### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [javamanatee/matthew-arnold_culture-and-anarchy#1]
# General Issues:

- [x] After completing the following changes, re-run `se build-toc .` and commit the change.

# chapter-2.xhtml:

- [x] You need to revert the change stablishing --> establishing. This is not a sound-alike spelling change.

# chapter-5.xhtml:

- [x] Headers that are entirely non-English-language are not italicized ([SEMOS 7.2.7](https://standardebooks.org/manual/1.7.4/single-page#7.2.7)). You can simplify it as `<p epub:type="title" xml:lang="la">Porro Unum Est Necessarium</p>`.

# content.opf:

- [x] I would like you to add a production note about Renascence vs. Renaissance. It's easier to find out in a production note than hunting down a specific endnote.

**Comment by javamanatee** [comment]
Changes done, it is back over to you.
